### ISSUE TITLE
Custom data attributes (dataset /  data-*) support

### ISSUE THREAD

**Issue by Janghou** [WICG/sanitizer-api#191] opened 2023-04-15 11:00 UTC
Trying out the new API in Chromium and Firefox, I was unable to allow a data-key attribute.

Any data-* attribute was filtered out by default, and something like this did not work:
````
`<li data-key="id1">apple</li>`
new Sanitizer({allowAttributes: { "data-key": ["li"], "data-*": ["li"] }
````

Wat should be the right syntax for this to work? 
And shouldn't custom data attributes be allowed by default?

**Comment by annevk** [comment] 2023-10-18 11:25
This also came up in #188. We need some kind of syntax whereby you can wildcard akin `data-*` for this.

**Comment by mozfreddyb** [comment] 2024-01-23 11:57
Duplicate of #188.

**Closed by mozfreddyb** 2024-01-23 11:57 UTC
Labels: v1
